### ISSUE TITLE
vtt 亂碼

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#14]
rails開utf8的設定
可能是加header

# 參考
https://developer.mozilla.org/zh-TW/docs/Web/API/Web_Video_Text_Tracks_Format

**Comment by leo424y** [comment]
果然是頁面預設編碼非 utf-8 而是 big 5

找到一個手動改編碼的瀏覽器外掛解
http://www.deep-watch.net/en/blog/bring-character-encoding-menu-back-to-chrome-with-extension

還在試程式解

**Comment by sih4sing5hong5** [comment]
毋知佮in有關無
https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/Content-Type
https://github.com/rails/rails/issues/8661#issue-9585195

**Comment by leo424y** [comment]
發問rails社群回覆也是說 content-type 設定的關係 http://railsfun.tw/t/topic/1512/4 已採用 其解法

**Comment by sih4sing5hong5** [comment]
伊是講佇nginx面頂設定utf-8
https://www.cyberciti.biz/faq/nginx-set-http-content-type-response-header-to-charset-utf8/
