### ISSUE TITLE
openstack加硬碟

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#17]
- [x] 了解如何擴充openstack容量

**Comment by leo424y** [comment]
[osCloudUserManual.pdf](https://github.com/twgo/tw-on-youtube/files/1630076/osCloudUserManual.pdf)
Create Volume p.19-22 @sih4sing5hong5 請參見說明書，可在VM另掛硬碟

**Comment by sih4sing5hong5** [comment]
好，看起來這無LVM，到時你才試好矣 XD
