### ISSUE TITLE
新增已存之格式欄位

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#19]
除了格式本身以外

咱tsang尾仔敢有討論欲存`實際的path`無？
存path是以後改路徑的做伙，咱無需要去維護舊的影片

抑是有這個需求的時陣才做migration？

## update_format_downloaded
- [x] spec 
- [x] db
- [x] code

**Comment by leo424y** [comment]
path有需求時再做migration即可，目前path是根據[格式/uploader_id]都能導出來，我會在下個pr加開已載之格式欄位
