### ISSUE TITLE
url unique

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#20]
其實愛用youtube id來做unique
因為playlist有可能指去仝款的影片

**Comment by leo424y** [comment]
因為單位youtube id 在playlist無法直接取得，但值得試試，可以的話應以id當unique
又若抓同一支影片會自動覆蓋，只是多花工很不聰明
ps. 下playlist指令目前在youtube-dl.rb gem 尚有bug(噴錯，影片有下載，但無法回傳影片data)我可能要自己解一下才能用

**Comment by sih4sing5hong5** [comment]
替in送PR XD

**Comment by leo424y** [comment]
https://github.com/layer8x/youtube-dl.rb 超過一年沒維護了，可能要clone回來自己改；

但我有想到懶一點的解法是：

因為gem拋出的
youtube-dl script照樣會執行

等整個playlist影片載完後，把檔名附加的youtube id 一支支撈出來再回推影片其它資訊，後面與單支影片一樣操作，因為清單已載，載的部分會略，不會花重覆工，接著，搬動照常運作。


我這週會先試這招
