### ISSUE TITLE
large file server 架設研究

### ISSUE THREAD

**Issue by leo424y** [twgo/tw-on-youtube#24]
- [x] new open stack VM
- [x] 300G
- [x] ~~ftp service~~  GIT!
- [x] install git-lfs
https://github.com/git-lfs/git-lfs/wiki/Installation
```
Ubuntu
Similar to Debian 7, Ubuntu 12 and similar Wheezy versions need to have a PPA repo installed to get git >= 1.8.2

sudo apt-get install software-properties-common to install add-apt-repository (or sudo apt-get install python-software-properties if you are on Ubuntu <= 12.04)
sudo add-apt-repository ppa:git-core/ppa
The curl script below calls apt-get update, if you aren't using it, don't forget to call apt-get update before installing git-lfs.
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install

```
- [x] ssh login ihs, ci
ssh USER@HOST 'mkdir -p ~/.ssh;cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
https://blog.gtwang.org/linux/linux-ssh-public-key-authentication/

**Comment by sih4sing5hong5** [comment]
1. 去server `git init --bare` ，產生[git service](https://git-scm.com/book/zh-tw/v1/%E4%BC%BA%E6%9C%8D%E5%99%A8%E4%B8%8A%E7%9A%84-Git-%E5%9C%A8%E4%BC%BA%E6%9C%8D%E5%99%A8%E4%B8%8A%E9%83%A8%E7%BD%B2-Git)
2. [clone落來](https://stackoverflow.com/a/16134428/3640653)

**Comment by leo424y** [comment]
好帥！ 簡單明了

**Comment by leo424y** [comment]
好帥！ 簡單明了

**Comment by sih4sing5hong5** [comment]
1. 咱會當用ssh push資料入去
2. ci的docker會當用ssh掠資料落來

1佮2認證無仝，我予你我的ssh key，2你產生一支
1佮2無sudo權限

**Comment by leo424y** [comment]
好的user設定收到，server硬體規格再麻煩一下

**Comment by sih4sing5hong5** [comment]
硬體規格較單純的代誌，你就先寫，我才看就好矣 
openstack我印象會當換cpu佮ram，應該無要緊
1CPU 2G RAM  300G HD

**Comment by leo424y** [comment]
1CPU 2G RAM 300G HD
OK 我先開這個規格

**Comment by sih4sing5hong5** [comment]
git lfs 設定好矣通知我一聲~~

**Comment by leo424y** [comment]
第一次管linux，已進行以下步驟
```
useradd ihc -m
用ihc在 
~/.ssh/authorized_keys' 
填你的 public key
id_rsa.pub
```
順利的話在你電腦
ssh ihc@172.16.3.126 應能登入lfs ?

另已安裝 git-lfs by
https://github.com/git-lfs/git-lfs/wiki/Installation

若有不對之處，請多指導

**Comment by sih4sing5hong5** [comment]
好～～我欲用的時陣才閣看有啥有欠，到時才麻煩你
