### ISSUE TITLE
使用 Jenkins CI

### ISSUE THREAD

**Issue by leo424y** [twgo/tw-on-youtube#28]
- [ ] 需求文件準備
- [ ] https://hub.docker.com/_/jenkins/
- [ ] 安裝
- [ ] 設定
- [ ] 試用
- [ ] 依需求試用

# 需求
- 聲學模型需要走一兩工
- rails管理系統設定指定的commit hash，傳hash佮別的參數予ci
- ci做好通知rails管理系統

**Comment by sih4sing5hong5** [comment]
我加`rails管理系統設定指定的commit hash，傳hash佮別的參數予ci`

**Comment by sih4sing5hong5** [comment]
https://hub.docker.com/_/jenkins/

**Comment by leo424y** [comment]
https://github.com/twgo/twgo-ci/issues/1 移到並已加   @sih4sing5hong5  / dev team 為admin
