### ISSUE TITLE
Rails 實驗管理系統

### ISSUE THREAD

**Issue by leo424y** [twgo/tw-on-youtube#29]
是否也是獨立一台VM不與其它VM互相干擾?
任務：
實驗輸入、顯示結果

需求投影片
https://hackmd.io/p/Hk0eeAHHG#/

**Comment by sih4sing5hong5** [comment]
需求投影片
https://hackmd.io/p/Hk0eeAHHG#/

**Comment by leo424y** [comment]
已開 repo https://github.com/twgo/twgo-exp 加 dev team 為admin
