### ISSUE TITLE
統一下載影片資料夾

### ISSUE THREAD

**Issue by leo424y** [twgo/tw-on-youtube#30]
youtube-dl 會自動檢查下載資料夾有沒有影片，故統一存檔較方便，不分user

- [x] 翻youtube-dl, 或youtube-dl gem改存檔root位置
https://github.com/rg3/youtube-dl#how-do-i-put-downloads-into-a-specific-folder
Use the -o to specify an output template, for example -o "/home/user/videos/%(title)s-%(id)s.%(ext)s". If you want this for all of your downloads, put the option into your configuration file.
- [x] youtube-dl內建分資料夾，可自訂，因此仍可依檔案類型與uploader_id存片
- [x] 依檔案類型分opus與mp4(+vtt)
- [x] vtt與mp4方一起方便播放時自動抓字幕如vlc player支援同folder自動抓字幕/切換語系。 
- [x] 移掉原來自己寫的move_file
- [x] 多片噴錯下載暫無解，故下載清單將只留清單url作判別，判別有沒有抓過youtube-dl會幫我們做！
- [x] 多片載了多少也就不必檢查了，youtube-dl時就會幫我們做完
- [x] youtube-dl內建避免重覆抓片
https://github.com/rg3/youtube-dl#how-do-i-download-only-new-videos-from-a-playlist

**Comment by sih4sing5hong5** [comment]
`下載清單噴錯`是啥意思

**Comment by leo424y** [comment]
gem youtube-dl.rb 大量下載時不會回傳清單內容資訊。單片正常。此bug暫不影響我們抓片

**Comment by leo424y** [comment]
#31
