### ISSUE TITLE
設定ci一定愛過才會當merge

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#32]
settings=>branch=>master

加travis ci，coverage看你欲加無

**Comment by leo424y** [comment]
<img width="766" alt="screen shot 2018-02-02 at 11 15 14 am" src="https://user-images.githubusercontent.com/1384394/35714914-692c3390-080a-11e8-8ec8-a916dbcdb3de.png">
ci 本來有加 coverage 手滑勾一下，不知到幾%不給過 XDD ，到時再看看

**Comment by sih4sing5hong5** [comment]
佇coverall的專案內底會當設定

**Comment by leo424y** [comment]
<img width="635" alt="screen shot 2018-02-02 at 2 48 12 pm" src="https://user-images.githubusercontent.com/1384394/35720345-2d791480-0828-11e8-9428-b12b4ac4f921.png">
coverall內有！我先設80看看

**Comment by sih4sing5hong5** [comment]
第兩个decrease彼个意思是：這擺pr，降偌濟%，愛認為失敗
