### ISSUE TITLE
掠影片

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/tw-on-youtube#6]
ps. 影片先留起來，因為有的有字幕

# Single Video download
- [x] core library test with url
- [x] input (V url) after add， pending 下載中... while not process
- [x] sidekiq work for background download
- [x] after download (C)， change  status , log video info to Video
- [x] log ( M video ) id, title, uploader, duration and more...
- [x] move file to uploader
- [x] move all file to uploader /try
- [x] move all file to uploader
- [x] move diff type file to type/uploader /try
- [x] move diff type file to type/uploader
- [x] download subtitle with video /try
- [x] download subtitle with video
- [x] core library test with options
```
#best audio options
      'extract-audio': true,
      'audio-format': 'opus',
      'audio-quality': 0,
```
- [x] add audio info abr/acodec 編碼/位元率
- [x] add social info of videos
- [x] download video and audio after input right link

  
  
log datas infos https://github.com/rg3/youtube-dl#output-template
```
        :url,
        :yid,
        :title,
        :thumbnail,
        :description,
        :duration,
        :filename,
        :uploader,
        :upload_date,
        :abr,
        :acodec,
        :status,
        :tags,
        :location,
        :view_count,
        :like_count,
        :dislike_count,
        :repost_count,
        :average_rating,
        :comment_count,
        :age_limit,
        :autonumber,
        :playlist,
        :playlist_id,
        :playlist_title,
        :playlist_uploader,
        :playlist_uploader_id,
```

**Comment by leo424y** [comment]
- [ ] input (V url)
- [ ] download (C)  status
- [ ] log ( M video ) id, title, uploader, duration
- [ ] move file to folder/uploader
- [ ] tag (type) video, audio, subtitles

Model

status 下載狀態，success, error
title 名稱，預設為來源名稱
folder 來源資料夾，預設為 上傳者
tag 類別標記以便取得，預設無，可建 subtitle, format

**Comment by leo424y** [comment]
#13
