### ISSUE TITLE
下載音檔格式探究

### ISSUE THREAD

**Issue by leo424y** [twgo/tw-on-youtube#9]
分析下載的影片如何得到最好的音質

- [x] 開發中測試中同時累計抓下來的格式分佈    
1/8高老師說到，多人語音較接近需求，或許有音頻做後設分析並加tag                                                                                                                              

opus>m4a

**Comment by sih4sing5hong5** [comment]
這是後壁的分析，等網站穩定才來處理遮的代誌

**Comment by leo424y** [comment]
實測下載之原生音檔格式多以opus居多，故音檔以opus存

**Comment by sih4sing5hong5** [comment]
處理到 https://github.com/twgo/tw-on-youtube/wiki/%E9%9F%B3%E8%A8%8A%E8%BE%A8%E8%AD%98%E7%9A%84%E5%BD%B1%E9%9F%BF 矣
